server:
  port: 8989

spring:
  datasource:
    #mysql8
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/241118-cms?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 1234
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #新增内容：上传文件大小配置
  servlet:
    multipart:
    # 单个文件上传的最大大小 默认为 1MB
    max-file-size: 10MB
    # 单次请求文件上传的最大大小 默认值为 10MB
    max-request-size: 100MB

  # 文件上传相关配置
upload:
  # 七牛云OSS相关配置
  OSS:
    # 配置AK
    accessKey: "KuZHcjj75tYneZjparxp6hyQOcBoZTAJllvy1hzz"
    # 配置SK
    secretKey: "7rXshOv5buImn3-u3GgS1mbJGNzX8wDILEe40qge"
    # 配置桶
    bucket: "fallcicada-workspace"
    # 配置基础域名
    baseUrl: "https://portal.qiniu.com/cdn/domain/sswdsbu7d.hd-bkt.clouddn.com"

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 雪花算法全局设置
      id-type: assign_id
      # 全局配置 逻辑删除字段及取值
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

mybatis:
  configuration:
    #日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰
    map-underscore-to-camel-case: true
  # mapper.xml 文件夹所在位置
  mapper-locations: classpath:mapper/**/*.xml

